name: Build

on: [push,]

jobs:
  build_CM4:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build docker images
        run: docker buildx build .devcontainer/
      - name: Run tests
        run: docker run -it -v $PWD:/srv -w/srv local make -C Makefile/CM4